name: PythonAnywhere Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 

    - name: Deploy to PythonAnywhere
      uses: davidwells/python-anywhere-deploy-action@v1
      with:
        pythonAnywhereUsername: ${{ secrets.PYTHONANYWHERE_USERNAME }}  # PythonAnywhere kullanıcı adı
        pythonAnywherePassword: ${{ secrets.PYTHONANYWHERE_PASSWORD }}  # PythonAnywhere parolası
        pythonAnywhereDomain: 'yourdomain.pythonanywhere.com'  # PythonAnywhere uygulamanızın domain'i
